### ISSUE TITLE
Simple alarm trigger bug (fix provided)

### ISSUE THREAD

**Issue by philipp-fischer** [ics-py/ics-py#269]
If an event alarm has its trigger set to `timedelta(0)`, the string serialization will fail although it should not.
Having the trigger at the same time as the event begins is a common case and should be supported.
Below, I provide a simple way to fix this. Let me know if you need a PR for this.

**Environment**
Bug should be independent of this but still:
ICS version: 0.7
Python 3.9.0
Windows

**Minimal working example**

```
c = Calendar()
e = Event()
e.begin = '2021-01-01 11:00:00'
e.duration = timedelta(minutes=30)
e.alarms = [DisplayAlarm(timedelta(minutes=0))]
e.name = "Test Event"
c.events.add(e)
print(str(c))  # Raises "ValueError: Alarm must have a trigger"
```

**Suggested fix**
In `ics/serializers/alarm_serializer.py:11` change `if not alarm.trigger` to `if alarm.trigger is None`.

Furthermore, the serialization needs to support zero time deltas:
In `ics\utils.py` fix the function `def timedelta_to_duration(dt: timedelta) -> str`,
by changing

```
    if dt.total_seconds() >= 0:
        return res
    else:
        return "-%s" % res
```
to
```
    if dt.total_seconds() > 0:
        return res
    elif dt.total_seconds() < 0:
        return "-%s" % res
    else:
        return "P0D"
```

**Comment by C4ptainCrunch** [comment]
Hi @philipp-fischer !

Thank you for your report ! We changed a lot of the serialization code since the last version (0.7). Could you check if the error still happens on master ? You can use `pip install git+https://github.com/C4ptainCrunch/ics.py.git` to try.

**Comment by N-Coder** [comment]
I guess this issue is already fixed and the fix is waiting for 0.7.1 to be released. See #254.
I'm pretty sure this is also fixed on 0.8.

**Comment by philipp-fischer** [comment]
Thanks @C4ptainCrunch and @N-Coder,
I just checked the version on `main` branch, and it seems many things have changed.
However, the bug is not fixed, things got worse now.

Here's my modified test code:

    c = Calendar()
    e = Event()
    e.begin = datetime.fromisoformat('2021-01-01 11:00:00')
    e.duration = timedelta(minutes=30)
    e.alarms = [DisplayAlarm(timedelta(minutes=0))]
    e.name = "Test Event"
    c.events.append(e)
    print(str(c.serialize()))

The output is

    BEGIN:VCALENDAR
    VERSION:2.0
    PRODID:ics.py - http://git.io/lLljaA
    BEGIN:VEVENT
    UID:34591728-a889-4a9d-befb-2d197894384b@3459.org
    DTSTAMP:20210131T075422Z
    BEGIN:VALARM
    END:VALARM
    DTSTART:20210101T110000
    DURATION:PT30M
    END:VEVENT
    END:VCALENDAR

So it serializes to an **empty** alarm (not valid iCalendar format).

The bug is very similar to the bug in the previous version and can be found in `ics.py\src\ics\converter\value.py` in `AttributeValueConverter.serialize()`:

    value = self.get_value(component)
    if value:

Again, the if statement is bad. You should use `if value is not None:`. You should do this for all kinds of similar checks in the code. It's just safer.

But even after fixing it, bugs remain (I haven't had the time to fix them all):

- Serialization of the alarm itself (without calendar) works after the above fix, but serializing the whole calendar again gives an empty alarm
- Even when using a trigger that is not zero, the alarm does not contain a `DESCRIPTION` and `ACTION`, although both are required to create a valid iCalendar (check it here: https://icalendar.org/validator.html). The previous version of `ics.py` had fewer bugs..

**Comment by N-Coder** [comment]
#293 fixes the Alarm problems you mentioned, including a [test case](https://github.com/ics-py/ics-py/pull/293/files#diff-f045b281a7b2808e71f7e76f9107b95841146f52b5f0f63b119dbddcabd23f02) that should cover all this. Could you check whether everything works with the code from that branch? Please note that I change the names of some of the Alarm attributes to be more aligned with the RFC.
