### ISSUE TITLE
Quickstart examples are broken

### ISSUE THREAD

**Issue by mfncooper** [ics-py/ics-py#316]
I just installed ics v0.7 and tried to create an ics file using the examples in the Quickstart. I found two issues:

First, this line:
```python
e.begin = '20140101 00:00:00'
```
results in this exception:
```python
arrow.parser.ParserError: Could not match input to any of ['YYYY-MM-DD HH:mm:ss'] on '20200112 09:00:00'
```
Changing the format to match what's in the exception message fixes the issue.

Second, this line:
```python
    f.write(c)
```
results in this exception:
```python
TypeError: write() argument must be str, not Calendar
```
Wrapping `str()` around the argument fixes the issue.

These are not major issues, obviously, but for someone just trying out the ics package for the first time, it gives a rather negative impression, and makes me wonder if I should be looking for a better package to use. If the very first page of the docs has errors, frankly it does not bode well for the overall quality of the package.

**Comment by N-Coder** [comment]
Hey, thanks for the heads up! I guess this is already fixed by #263, which is not really visible since we haven't had a 0.7.1 since then. I'll try to fix that.

**Comment by tedmiston** [comment]
Just a heads up that this is still broken in the current docs.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/366688/175788329-103a1fdc-1a9b-4c5a-a592-b8687ba89a3a.png">

**Comment by N-Coder** [comment]
It's fixed now with the 0.7.1 release :wink:
